### ISSUE TITLE
Add custom tags to logs

### ISSUE THREAD

**Issue by friedcode** [DataDog/browser-sdk#885] opened 2021-06-08 09:18 UTC
I'd like to be able to add custom tags to every log message sent, so I can filter by these custom tags in the log explorer.
Currently only a few tags are created from the Initialization parameters, like version, env or service.

**Comment by bcaudan** [comment] 2021-06-08 09:29
👋 that seems to be a duplicate of https://github.com/DataDog/browser-sdk/issues/462, feel free to reopen otherwise.

**Closed as completed by bcaudan** 2021-06-08 09:29 UTC
