### ISSUE TITLE
🐛 huge performance drop with session replay recording & shadowRoots 

### ISSUE THREAD

**Issue by Brumor** [DataDog/browser-sdk#2269] opened 2023-05-29 13:53 UTC
**Describe the bug**

When starting with opened shadow roots a noticeable drop in performance is noticed. Here is what the performance tab looks like while typing in an input field: 

![image (1)](https://github.com/DataDog/browser-sdk/assets/19175088/77fa9820-c13c-41f5-a93a-6516dd8c9763)

![image (2)](https://github.com/DataDog/browser-sdk/assets/19175088/f0e6a20e-c4ec-4e93-94c2-30bede0c0ee0)

As you can see it's instrumentWrapper all the way down. For info, our site has both MFEs rendered in shadow roots as well as a design system where each elements are rendered through shadow roots, which end up making a lot of nested shadow roots in the document. I dug a bit though your code and my guess is that it could have to do with how every single shadow root element is being serialized when snapshots are taken, but i'm not sure.

Is it fixeable? Alternatively, if we could come up with a solution for this, like either throttling, or disable `initInputObserver` on specifix shadow-roots or even the whole app.

**Expected behavior**
Having session recording shouldn't impact performance.

**Comment by bcaudan** [comment] 2023-05-30 07:43
Hi @Brumor,

Could you share with us a setup allowing to reproduce this performance issue?

**Comment by Brumor** [comment] 2023-06-07 08:09
I contacted datadog's support to set up a meeting as I can't share the code here.

**Comment by rkapoor028** [comment] 2023-06-27 03:07
We are seeing similar issues after recent Shadow DOM support was introduced on our App. Did we reach on a conclusion regarding this issue?

**Comment by rkapoor028** [comment] 2023-06-27 19:58
We were able to reproduce and generate a profile for our issue, we see the exact same issue in our case. This is causing some performance issues for us since the support for Shadow DOM was introduced in this package. Is it possible to get a fix for this soon?

Please check this screenshot:
![image](https://github.com/DataDog/browser-sdk/assets/43480270/6cc5654f-50e3-4066-aa77-fc97c92f45a0)

**Comment by 1bberto** [comment] 2023-06-28 17:31
facing the same issue here on the version **4.42.2**

**Comment by BenoitZugmeyer** [comment] 2023-06-29 12:24
We'll follow up with @Brumor through our support process.

@rkapoor028 @1bberto it would be great if you could provide a way to reproduce the issue. Without more details, it'll be hard for us to understand what's going on.

**Comment by BenoitZugmeyer** [comment] 2023-06-30 09:13
This issue will probably be fixed by https://github.com/DataDog/browser-sdk/pull/2313. It'll be part of the next released, stay tuned

**Comment by BenoitZugmeyer** [comment] 2023-07-03 12:13
A fix has been released as part of v4.44.0. Let us know if you still experience the issue.

**Closed by BenoitZugmeyer** 2023-07-03 12:13 UTC
Labels: bug, need-info
