### ISSUE TITLE
🐛 Elements not being properly garbage collected with session replay

### ISSUE THREAD

**Issue by Brumor** [DataDog/browser-sdk#2424] opened 2023-09-12 14:33 UTC
**Describe the bug**

We noticed some performance issues recently with elements on the page not getting removed correctly and still occupying memory space leading to performance issues after a longer use / switching pages.

![image (2)](https://github.com/DataDog/browser-sdk/assets/19175088/d1515482-7b60-48b3-a0a2-9ff08e51d835)

The amount of detached Mutation Observers got us thinking that it might be a sort of memory leak due to session replay so we tested performance with and without and fair enough:
with session replay enabled:
![nodes-nectary-2 4-with-replay](https://github.com/DataDog/browser-sdk/assets/19175088/44104f88-d69e-453b-96dc-ea8bb7a5605c)

without session replay:
![nodes-nectary-2 4-no-replay](https://github.com/DataDog/browser-sdk/assets/19175088/9a473946-09c0-423a-aeea-2d609b9858db)

As you can see some nodes are still in memory when navigating within our app (in a SPA) with session replay. I guess it is related to #2269 and how session replay handles shadow-roots

**To Reproduce**

This is the same project as #2269 , I'd need to turn on a feature flag for you to test it again, let me know if you need it.

Anything we should be doing to makes sure the elements being observed and their mutation observer get removed correctly?

**Comment by BenoitZugmeyer** [comment] 2023-09-13 12:49
Hi @Brumor. I investigated a bit and couldn't reproduce any memory leak while recording webcomponents/shadow dom mutations. We use WeakMaps extensively to avoid leaking DOM nodes.

> This is the same project as https://github.com/DataDog/browser-sdk/issues/2269 , I'd need to turn on a feature flag for you to test it again, let me know if you need it.

I would love to try to reproduce your issue in your app. Could you send a message to support@datadoghq.com with instructions and mention me (Benoit Zugmeyer)? (the account you provided in the last issue does not seem to work anymore)

> Anything we should be doing to makes sure the elements being observed and their mutation observer get removed correctly?

Nothing I can think of.

**Comment by BenoitZugmeyer** [comment] 2023-10-04 13:53
Thank you for providing steps to reproduce. [A fix](https://github.com/DataDog/browser-sdk/pull/2451) is on its way.

**Comment by bcaudan** [comment] 2023-10-09 15:52
The fix has been released with browser-sdk@4.50.1.
Let us know if there is still an issue.

**Closed by bcaudan** 2023-10-09 15:52 UTC
Labels: bug
