### ISSUE TITLE
How to filter out aborted XHR requests from the error logs

### ISSUE THREAD

**Issue by hasryan** [DataDog/browser-sdk#362] opened 2020-04-15 21:15 UTC
We frequently see several logs with this pattern:

Message: `XHR error GET https://url-of-ajax-endpoint`
Stack trace: `Failed to load`

What we discovered is that these are not actually errors but are aborted XHR requests. We use a library called select2 which makes XHR requests as the user types an input. It's not uncommon for a single user interaction to generate several requests as they type their input string.

The select2 library is aborting in-flight XHR requests before it makes a new one as described here https://stackoverflow.com/a/37319150/7691972

I am curious what the best way is to either prevent these from being logged, or to distinguish these from other legitimate errors that may present similarly.

**Comment by bcaudan** [comment] 2020-04-16 12:26
Hi @hasryan,

It seems to me that this a duplicate of #308.
I could reopen otherwise.

**Comment by hasryan** [comment] 2020-04-16 17:23
Apologies! I saw that issue but it did not occur to me that these are all status code=0. Resolution for that one should enable me to filter these out so I will follow it instead.

**Comment by Lewischarlton93** [comment] 2023-07-13 12:05
This still appears to be an issue for us. These sort of logs are causing a lot of noise in our DataDog account. Did anyone come up with a solution to resolve these XHR errors? We're getting a high value on a daily basis with a few of our 3rd party's. 

Commenting here as the thread on #308 has been closed.

**Comment by BenoitZugmeyer** [comment] 2023-08-18 09:58
Thank you for bumping the issue. We'll see what we can do here. Filtering out aborted requests could be considered as a breaking change, but fortunately we have a major version coming.

**Comment by aethr** [comment] 2023-08-20 21:59
Thanks @BenoitZugmeyer for the update.

Understand it would be a breaking change for some. I imagine some teams might be interested on reporting/metrics around cancelled requests and/or network failures, but I would imagine it loses a lot of value if they're indistinguishable from each other.

From my understanding, requests are cancelled when:
- manually aborted with AbortController
- renderer issues a request for a DOM element (ie an image) but the DOM node is removed from the page before the request finishes
- user navigates to a new page while elements/requests of a page are still loading

I'm not an expert so this list may not be complete, but it seems that request cancellation happens on purpose as opposed to network failure which is unpredictable: the user's connection fails, the server times out, a firewall/adblock blocks the request, etc. These seem distinct from a logging perspective.

The simplest "fix" for my team would be not to send these error logs for aborted requests. We don't have to implement anything and our logs look a lot cleaner. But this may not work for every team.

A more flexible change might be to send some detail to distinguish aborted requests (ie, `aborted: true/false` or different log message) in the event. Then teams like mine could prevent the event in logs/RUM `beforeSend`, or allow the event through but have enough context in Datadog UI for improved reporting.

Just some ideas from a user, feel free to take or leave them. :smile:

**Comment by marc-wilson** [comment] 2023-10-11 20:11
I'm experiencing this as well. The cancellations are extremely noisy in our logs. I know I can filter them out in the datadog UI, but would rather prevent them from the source.

**Comment by aethr** [comment] 2023-10-11 21:28
@marc-wilson as my comment above, my team is filtering out all failed network requests (cancellations and unexpected failures) using this logic:

```js
      datadogLogs.init({
        // ... datadog config ...
        beforeSend: (event) => {
          // ... some other stuff ...

          // don't log network failures and cancellations
          if (event.error && event.http?.status_code === 0) {
            return false;
          }
        },
      });
```

**Comment by marc-wilson** [comment] 2023-10-11 21:41
Thanks, @aethr. I tried doing that but I don't see `event.http` ever truthy. It's `event.http` is always undefined.

Seems like the right solution though. But, not sure what drives the "population" of `event.http`

**Comment by marc-wilson** [comment] 2023-10-16 19:46
Never witnessed `event.http` being populated locally, but moved forward with the workaround anyways. I am no longer seeing any of the errors make it through so it is working.

Looking forward to this being enhanced to include. with `isAborted` flag

**Comment by thomas-lebeau** [comment] 2024-04-02 13:17
You have now access to `isAborted` property in beforeSend's context argument.

example:
```
datadogLogs.init({
        // ... datadog config ...
        beforeSend: (event, context) => {
          if (context.isAborted) {
            return false
          }
        },
      });
```

fixed in #2682 #2665

**Closed by thomas-lebeau** 2024-04-02 13:17 UTC
Labels: enhancement

**Comment by MichaelArnoldOwens** [comment] 2024-08-13 06:42
think the ts types also need to be updated, but this is a great step forward!!!
<img width="470" alt="image" src="https://github.com/user-attachments/assets/951d871a-c7f9-4e90-9455-06b21ae15cfc">

**Comment by BenoitZugmeyer** [comment] 2024-10-15 17:12
To make TypeScript happy, you could try:

```ts
if ('isAborted' in context && context.isAborted) {
```

**Comment by lyonsun** [comment] 2025-03-04 13:12
We are using CDN async script, would the above solution work within the script too?
