### ISSUE TITLE
Configure #isServerError() logic

### ISSUE THREAD

**Issue by randdusing** [DataDog/browser-sdk#776] opened 2021-03-31 21:53 UTC
I would like to raise an error for HTTP statuses greater than 400 rather than 500. Can we make this configurable?

https://github.com/DataDog/browser-sdk/blob/cd54b0dfc05a8c6f64c1fa6c2acfc4d0130c72f4/packages/core/src/domain/automaticErrorCollection.ts#L144-L146

**Comment by hdelaby** [comment] 2021-04-01 08:36
Hey @randdusing, we are actually planning on deprecating RUM errors generated from RUM resources. Is there any specific reason why you would need actual errors generated for these  4xx requests?

You can currently track 4xx resources with the following query:
![RUM Analytics  Datadog 2021-04-01 at 10 34 26 AM](https://user-images.githubusercontent.com/21019740/113266716-dee26380-92d5-11eb-9076-a6f156d367c4.jpg)

**Comment by randdusing** [comment] 2021-04-01 14:59
I need to see details of the error, but I believe the example above doesn't allow you to see any details of the error itself.

**Comment by bcaudan** [comment] 2021-12-13 15:24
No more network error events for RUM.
Duplicate of #1203 for Logs.

**Closed by bcaudan** 2021-12-13 15:24 UTC
Labels: enhancement, logs
