### ISSUE TITLE
RUM Init fails on letters in version strings

### ISSUE THREAD

**Issue by rnarayana** [DataDog/browser-sdk#1623] opened 2022-07-01 12:46 UTC
Hi, I have the following init code in a react app. It fails silently (or does nothing - there are no errors anywhere), and doesn't send anything to datadog or initialize the internalContext _for the following version string_ "2.5.0-PullRequest16000.4833", but it works fine for a version like "2.5". I looked at the version [rules](https://docs.datadoghq.com/getting_started/tagging/#define-tags), and it seems like I am following them. But the library seems to support only numbers, and not letters. Is my understanding correct? Is this the expected behaviour?

`
datadogRum.init({
              applicationId: configJSON.datadog.applicationId,
              clientToken: configJSON.datadog.clientToken,
              site: configJSON.datadog.site,
              service: configJSON.datadog.service,
              env: configJSON.appEnv,
              version: configJSON.appVersion,  // <<<------
              sampleRate: 100,
              premiumSampleRate: 0,
              trackInteractions: true,
              trackFrustrations: true,
              allowedTracingOrigins: [window.location.origin]
            });
`

**Comment by amortemousque** [comment] 2022-07-04 11:59
Hi @rnarayana,

I can't recreate the issue on my side. 
Do you have a minimal reproductible code example?
What is your setup and SDK version?

**Comment by rnarayana** [comment] 2022-07-07 12:02
I'll try to add a repro over the weekend. This happens when hosted on nginx+aks but not locally. I'll try to isolate the issue.

**Comment by rnarayana** [comment] 2022-07-10 09:47
Ok, I'm unable to create a minimum repro.. When I created something from scratch using create-react-app and hosted on nginx on docker, it is still working properly. I guess it might be some other weird issue with my actual application, maybe the way things are wired up.

I guess this can be closed. Just FYI, for now, my workaround is to truncate anything after - in versions like 1.2.3-PullReuqest.5050

**Comment by BenoitZugmeyer** [comment] 2022-07-19 16:45
I cannot reproduce either. Maybe check that the version does not start or end with a blank character?

Closing this issue for now, feel free to re-open if you found anything!

**Closed by BenoitZugmeyer** 2022-07-19 16:45 UTC
Labels: need-info
